version: "3.9"

services:
  postgres:
    container_name: my_notes_db
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: "${db_user_env}"
      POSTGRES_PASSWORD: "${db_pass}"
